# Generated by Django 2.2.4 on 2020-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='992Y4QSE', max_length=20, primary_key=True, serialize=False),
        ),
    ]
