# Generated by Django 2.2.4 on 2020-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200221_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='M0OMEXUM', max_length=20, primary_key=True, serialize=False),
        ),
    ]
