# Generated by Django 2.2.3 on 2020-02-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200221_2024'),
        ('main', '0002_auto_20200221_1611'),
    ]

    operations = [
    ]
