# Generated by Django 2.2.4 on 2020-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200221_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='NBW83H47', max_length=20, primary_key=True, serialize=False),
        ),
    ]
