# Generated by Django 2.2.4 on 2020-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200221_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='3NJRVU6N', max_length=20, primary_key=True, serialize=False),
        ),
    ]
