# Generated by Django 2.2.4 on 2020-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='RX27W0ZC', max_length=20, primary_key=True, serialize=False),
        ),
    ]
