# Generated by Django 2.2.4 on 2020-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200223_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='JFVIV6IX', max_length=20, primary_key=True, serialize=False),
        ),
    ]
