# Generated by Django 3.0.3 on 2020-02-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200223_2250'),
        ('main', '0008_auto_20200222_1152'),
    ]

    operations = [
    ]
