# Generated by Django 3.0.3 on 2020-02-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200224_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='AY5JCXJ5', max_length=20, primary_key=True, serialize=False),
        ),
    ]
