# Generated by Django 3.0.3 on 2020-02-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200224_0056'),
        ('main', '0008_auto_20200224_0310'),
    ]

    operations = [
    ]
