# Generated by Django 3.0.3 on 2020-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200224_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='1KX0KE1U', max_length=20, primary_key=True, serialize=False),
        ),
    ]
