# Generated by Django 2.2.4 on 2020-02-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='I6M6TBG1', max_length=20, primary_key=True, serialize=False),
        ),
    ]
