# Generated by Django 3.0.3 on 2020-02-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20200222_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='8KBDD4GA', max_length=20, primary_key=True, serialize=False),
        ),
    ]
