# Generated by Django 3.0.3 on 2020-02-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20200224_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='8LICABKG', max_length=20, primary_key=True, serialize=False),
        ),
    ]
